version: "3.6"
services:
  postgres:
    container_name: "${STAGE}-${APP_NAME}-postgres"
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  hapi:
    container_name: "${STAGE}-${APP_NAME}-hapi"
    build: ./hapi
    ports:
      - "9090:9090"
    volumes:
      - ./hapi:/usr/app
    environment:
      PORT: "${PORT}"
      HOST_ADDRESS: "${HOST_ADDRESS}"
      HASURA_URL: "${HASURA_URL}"
      HASURA_ADMIN_SECRET: "${HASURA_ADMIN_SECRET}"
    depends_on:
      - "postgres"
    restart: on-failure
  hasura:
    container_name: "${STAGE}-${APP_NAME}-hasura"
    image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
    ports:
      - "8085:8080"
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "${DATABASE_URL}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE}"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "${HASURA_GRAPHQL_ENABLED_LOG_TYPES}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
    depends_on:
      - postgres
    restart: on-failure
